#ifndef MEDIANBLURPLUGIN_GLOBAL_H
#define MEDIANBLURPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEDIANBLURPLUGIN_LIBRARY)
#  define MEDIANBLURPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MEDIANBLURPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MEDIANBLURPLUGIN_GLOBAL_H
