#ifndef MEDIANFILTERPLUGIN_GLOBAL_H
#define MEDIANFILTERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEDIANFILTERPLUGIN_LIBRARY)
#  define MEDIANFILTERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MEDIANFILTERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MEDIANFILTERPLUGIN_GLOBAL_H
